name: mobility-IGC_By_HAMZA_CHOKRI

        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry tox tox-gh-actions
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry sphinx sphinx_rtd_theme sphinx-copybutton
          pip install -r requirements.txt

